# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  riverwisedetroit.org:
    site_hosts:
      - canonical: riverwisedetroit.org
        redirects:
          - www.riverwisedetroit.org
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:bnchdrff/riverwisedetroit.org.git
    repo_subtree_path: site
    branch: master
    admin_email: anonyben@gmail.com
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
